services:
  nest-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
    depends_on:
      - ollama-service
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  ollama-service:
    image: ollama/ollama:0.20.2-rocm
    container_name: ollama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: 
      - /bin/bash
      - -c
      - |
        ollama serve &
        echo "Iniciando servidor..."
        until (echo > /dev/tcp/localhost/11434) >/dev/null 2>&1; do 
          sleep 1
        done
        echo "Servidor listo. Descargando modelo..."
        ollama pull $$MODEL_NAME
        wait
    ports:
      - "11434:11434"
    environment:
      - MODEL_NAME=danielsheep/Qwen3-Coder-30B-A3B-Instruct-1M-Unsloth:UD-IQ3_XXS
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  db-service:
    image: postgres:18-alpine3.23
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chat_ia
    volumes:
      - db_storage:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  ollama_storage:
  db_storage: